USE [StudentPerformance]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [StudentPerformance].[DimLunch](
	[LunchSK] [int] IDENTITY(1,1) NOT NULL,
	[Lunch] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[LunchSK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


